"""External-validation protocol contracts and deterministic persistence."""

from test_cartographer.validation.enums import (
    ValidationArtefactKind,
    ValidationArtefactProducer,
    ValidationAuthenticationRequirement,
    ValidationFindingKind,
    ValidationLifecycleStage,
    ValidationOperatorDifficulty,
    ValidationResultConfidence,
    ValidationRunCompletion,
    ValidationStopCondition,
    ValidationTargetControl,
    ValidationTargetDifficulty,
    ValidationTargetFamiliarity,
    ValidationWorkflowKind,
    ValidationWorkflowReuseIntent,
)
from test_cartographer.validation.fingerprints import (
    compute_package_fingerprint,
    compute_run_fingerprint,
    compute_target_fingerprint,
    validate_package_fingerprint,
    validate_run_fingerprint,
    validate_target_fingerprint,
)
from test_cartographer.validation.io import (
    export_validation_schemas,
    load_validation_evidence_manifest,
    load_validation_run,
    load_validation_target_profile,
    save_validation_evidence_manifest,
    save_validation_run,
    save_validation_target_profile,
)
from test_cartographer.validation.operator_acceptance import compute_working_tree_fingerprint
from test_cartographer.validation.package import (
    ValidationPackageSource,
    build_validation_evidence_package,
    verify_validation_evidence_package,
)
from test_cartographer.validation.models import (
    ValidationEvidenceEntry,
    ValidationEvidenceManifest,
    ValidationFinding,
    ValidationFindingReference,
    ValidationOperatorAssessment,
    ValidationProductReference,
    ValidationRun,
    ValidationRuntimeEnvironment,
    ValidationTargetProfile,
    ValidationTiming,
)
from test_cartographer.validation.service import (
    create_validation_evidence_manifest,
    create_validation_run,
    create_validation_target_profile,
)

__all__ = [
    "ValidationArtefactKind",
    "ValidationArtefactProducer",
    "ValidationAuthenticationRequirement",
    "ValidationEvidenceEntry",
    "ValidationEvidenceManifest",
    "ValidationFinding",
    "ValidationFindingKind",
    "ValidationFindingReference",
    "ValidationLifecycleStage",
    "ValidationOperatorAssessment",
    "ValidationPackageSource",
    "ValidationOperatorDifficulty",
    "ValidationProductReference",
    "ValidationResultConfidence",
    "ValidationRun",
    "ValidationRunCompletion",
    "ValidationRuntimeEnvironment",
    "ValidationStopCondition",
    "ValidationTargetControl",
    "ValidationTargetDifficulty",
    "ValidationTargetFamiliarity",
    "ValidationTargetProfile",
    "ValidationTiming",
    "ValidationWorkflowKind",
    "ValidationWorkflowReuseIntent",
    "build_validation_evidence_package",
    "compute_package_fingerprint",
    "compute_working_tree_fingerprint",
    "compute_run_fingerprint",
    "compute_target_fingerprint",
    "create_validation_evidence_manifest",
    "create_validation_run",
    "create_validation_target_profile",
    "export_validation_schemas",
    "load_validation_evidence_manifest",
    "load_validation_run",
    "load_validation_target_profile",
    "save_validation_evidence_manifest",
    "save_validation_run",
    "save_validation_target_profile",
    "validate_package_fingerprint",
    "validate_run_fingerprint",
    "validate_target_fingerprint",
    "verify_validation_evidence_package",
]
